### ISSUE TITLE
Cannot download models

### ISSUE THREAD

**Issue by KoichiYasuoka** [360er0/COMBO#15]
Hi @360er0 I've just tried to download some models from https://github.com/360er0/COMBO#trained-models but been forbidden with "You don't have permission to access this resource". How do I get the permission?

**Comment by 360er0** [comment]
Hi, this repo is deprecated. The current one is here: https://gitlab.clarin-pl.eu/syntactic-tools/combo It contains a PyTorch implementation of COMBO and all models. They are better too :)

**Comment by KoichiYasuoka** [comment]
Thank you @360er0 for the information of new COMBO, but I couldn't find `kk_ktb` there. Please tell me where the "better" model of Kazakh is. Thank you very much for your kind reply in advance.

**Comment by 360er0** [comment]
You're right. There is no "new" Kazakh model there and the "old" model seems to be lost :( I would recommend using: https://github.com/Hyperparticle/udify or https://stanfordnlp.github.io/stanza/index.html
