### ISSUE TITLE
API

### ISSUE THREAD

**Issue by gcelano** [360er0/COMBO#3]
I am trying to make available the my COMBO model as a REST API using Flask.

Is `params.test` in `test_data = loader.load(params.test)` a file path?

What of kinf of object is `pred` in `pred = parser.predict(test_data)`?

**Comment by 360er0** [comment]
Ad 1. Yes, it is a file path (string) to test file.
Ad 2. It is a `List[utils.Tree]`.

**Comment by gcelano** [comment]
I have been able to extract the relevant code to allow output of a parsed text without saving. However, reading a text directly (not from opening a file) turns out to be harder. load() in TSVLoader does not accept pure text when I delete `open(filename, 'r') as f`. Is TxtLoader() ever used? There is another load() there, which might be more relevant.

**Comment by 360er0** [comment]
I'm afraid there is currently no way to read text directly (not from file). You will need to write your own loader which outputs list of trees.
