### ISSUE TITLE
Error for few files

### ISSUE THREAD

**Issue by swapnilnikule** [360er0/COMBO#9]
2020-07-10 15:28:52.073246: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at conv_ops.cc:500 : Resource exhausted: OOM when allocating tensor with shape[100016,1,32,512] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
Traceback (most recent call last):
  File "main.py", line 307, in <module>
    pred = parser.predict(test_data)
  File "/root/Downloads/COMBO-master/parser.py", line 205, in predict
    batch_probs = self.model.predict_on_batch(batch)
  File "/usr/local/lib/python3.6/site-packages/keras/engine/training.py", line 1274, in predict_on_batch
    outputs = self.predict_function(ins)
  File "/usr/local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/usr/local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/usr/local/lib64/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1472, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[100016,1,32,512] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
	 [[{{node time_distributed_1/conv1d_1/convolution}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

[file-8.txt](https://github.com/360er0/COMBO/files/4902402/file-8.txt)
[file-13.txt](https://github.com/360er0/COMBO/files/4902408/file-13.txt)
[file-23.txt](https://github.com/360er0/COMBO/files/4902409/file-23.txt)
[file-25.txt](https://github.com/360er0/COMBO/files/4902410/file-25.txt)
[file-31.txt](https://github.com/360er0/COMBO/files/4902411/file-31.txt)
[file-32.txt](https://github.com/360er0/COMBO/files/4902412/file-32.txt)
[file-38.txt](https://github.com/360er0/COMBO/files/4902413/file-38.txt)

this files gave error and the model didnt predict anything.

**Comment by 360er0** [comment]
It looks like you don't have enough RAM to run the model. Does it work on other files? If yes, could you also attach the file for which the prediction works?

**Comment by swapnilnikule** [comment]
i have 8gb of RAM and i5 8th gen processor with MX130 GPU OS-LINUX

LIST OF FILES FOR WHICH THE PREDICTION WORKED:
[file-1.txt](https://github.com/360er0/COMBO/files/4906960/file-1.txt)
[file-2.txt](https://github.com/360er0/COMBO/files/4906962/file-2.txt)
[file-3.txt](https://github.com/360er0/COMBO/files/4906963/file-3.txt)
[file-4.txt](https://github.com/360er0/COMBO/files/4906964/file-4.txt)
[file-5.txt](https://github.com/360er0/COMBO/files/4906965/file-5.txt)
[file-6.txt](https://github.com/360er0/COMBO/files/4906966/file-6.txt)
[file-7.txt](https://github.com/360er0/COMBO/files/4906967/file-7.txt)
[file-9.txt](https://github.com/360er0/COMBO/files/4906968/file-9.txt)
[file-10.txt](https://github.com/360er0/COMBO/files/4906969/file-10.txt)
[file-11.txt](https://github.com/360er0/COMBO/files/4906970/file-11.txt)
[file-12.txt](https://github.com/360er0/COMBO/files/4906971/file-12.txt)
[file-14.txt](https://github.com/360er0/COMBO/files/4906972/file-14.txt)
[file-15.txt](https://github.com/360er0/COMBO/files/4906973/file-15.txt)
[file-16.txt](https://github.com/360er0/COMBO/files/4906974/file-16.txt)
[file-17.txt](https://github.com/360er0/COMBO/files/4906975/file-17.txt)
[file-18.txt](https://github.com/360er0/COMBO/files/4906976/file-18.txt)
[file-19.txt](https://github.com/360er0/COMBO/files/4906977/file-19.txt)
[file-20.txt](https://github.com/360er0/COMBO/files/4906978/file-20.txt)
[file-21.txt](https://github.com/360er0/COMBO/files/4906979/file-21.txt)
[file-22.txt](https://github.com/360er0/COMBO/files/4906980/file-22.txt)
[file-24.txt](https://github.com/360er0/COMBO/files/4906981/file-24.txt)
[file-26.txt](https://github.com/360er0/COMBO/files/4906982/file-26.txt)
[file-27.txt](https://github.com/360er0/COMBO/files/4906983/file-27.txt)
[file-28.txt](https://github.com/360er0/COMBO/files/4906984/file-28.txt)
[file-29.txt](https://github.com/360er0/COMBO/files/4906985/file-29.txt)
[file-30.txt](https://github.com/360er0/COMBO/files/4906986/file-30.txt)
[file-33.txt](https://github.com/360er0/COMBO/files/4906987/file-33.txt)
[file-34.txt](https://github.com/360er0/COMBO/files/4906988/file-34.txt)
[file-35.txt](https://github.com/360er0/COMBO/files/4906989/file-35.txt)
[file-36.txt](https://github.com/360er0/COMBO/files/4906990/file-36.txt)
[file-37.txt](https://github.com/360er0/COMBO/files/4906991/file-37.txt)
